openapi: 3.0.1
info:
  title: GetMobiluxCategoriesDataStart
  description: API Definition of GetMobiluxCategoriesDataStart
  version: 1.0.0
servers:
- url: http://localhost:8290/api/get_mobilux_categories_data_start
paths:
  /:
    get:
      responses:
        default:
          description: Default response
