openapi: 3.0.1
info:
  title: GetMobiluxCategoriesData
  description: API Definition of GetMobiluxCategoriesData
  version: 1.0.0
servers:
- url: http://localhost:8290/api/get_mobilux_categories_data
paths:
  /:
    get:
      responses:
        default:
          description: Default response
