openapi: 3.0.1
info:
  title: MobiluxIntegrationApiStartSequence
  description: API Definition of MobiluxIntegrationApiStartSequence
  version: 1.0.0
servers:
- url: http://localhost:8290/api/mobilux/start
paths:
  /:
    get:
      responses:
        default:
          description: Default response
