openapi: 3.0.1
info:
  title: MobiluxFeedIdSend
  description: API Definition of MobiluxFeedIdSend
  version: 1.0.0
servers:
- url: http://localhost:8290/mobilux/send
paths:
  /:
    post:
      responses:
        default:
          description: Default response
