openapi: 3.0.1
info:
  title: PSXFeedIdSend
  description: API Definition of PSXFeedIdSend
  version: 1.0.0
servers:
- url: http://localhost:8290/psx/send
paths:
  /:
    post:
      responses:
        default:
          description: Default response
