openapi: 3.0.1
info:
  title: PSXIntegrationApiStartSequence
  description: API Definition of PSXIntegrationApiStartSequence
  version: 1.0.0
servers:
- url: http://localhost:8290/api/psx/start
paths:
  /:
    get:
      responses:
        default:
          description: Default response
