openapi: 3.0.1
info:
  title: WexlGruppGetXml
  description: API Definition of WexlGruppGetXml
  version: 1.0.0
servers:
- url: http://localhost:8290/api/wexl_grupp/get_xml
paths:
  /:
    get:
      responses:
        default:
          description: Default response
