openapi: 3.0.1
info:
  title: WexlGruppGetXmlStart
  description: API Definition of WexlGruppGetXmlStart
  version: 1.0.0
servers:
- url: http://localhost:8290/api/wexl_grupp/get_xml_start
paths:
  /:
    get:
      responses:
        default:
          description: Default response
