openapi: 3.0.1
info:
  title: WexlGruppTelegrammSend
  description: API Definition of WexlGruppTelegrammSend
  version: 1.0.0
servers:
- url: http://localhost:8290/api/telegramm/send
paths:
  /:
    post:
      responses:
        default:
          description: Default response
