openapi: 3.0.1
info:
  title: WexlGruppApiStartSequence
  description: API Definition of WexlGruppApiStartSequence
  version: 1.0.0
servers:
- url: http://localhost:8290/api/job/start
paths:
  /:
    get:
      responses:
        default:
          description: Default response
